apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: kafka
  name: kafkaibdn
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: kafka
