apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30020
  selector:
    io.kompose.service: mongo-express
