apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: pyflask
  name: pyflask
spec:
  type: NodePort
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
      nodePort: 30010
  selector:
    io.kompose.service: pyflask
